/// @file blueprint_converter.cpp
/// Program entry point for blueprint_converter utility.
///
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Wednesday December 6 2017
/// * Documentation is generated by doxygen, see html/index.html

#include <iostream>

#include "args_blueprint_converter.h"
#include "error.h"
#include "yaml-cpp/yaml.h"

int main(int argc, char** argv)
{
    
    try
    {
        
        // Parse command line arguments
        args::blueprint_converter_t args;
        args.parse(argc, argv);
        
        // Parse input file
        YAML::Node ccp_yaml_in = YAML::LoadFile(args.ccp_yaml_in());
        
    } catch (const error_message_t& error) {
        
        std::cout << error.message() << '\n';
        
    }
    
    return 0;
    
}

