/// @brief Implementation of @ref error_message_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Saturday November 4 2017
/// * Documentation is generated by doxygen, see documentation/html_out/index.html

#include <string_view>
#include <vector>

#include "error.h"

const std::vector<std::string_view> error_message_t::error_names_ =
{
    "FILE_SIZE_FAILED",
    "FILE_READ_FAILED",
    "FILE_WRITE_FAILED",
    "JSON_SCHEMA_VIOLATION",
    "MODE_MISSING",
    "MODE_INVALID",
    "ITEM_ATTRIBUTES_OUT_MISSING",
    "ITEM_ATTRIBUTES_IN_MISSING",
    "STATION_ATTRIBUTES_IN_MISSING",
    "PRICES_OUT_MISSING",
    "UNKNOWN_ORDER_TYPE",
    "EVE_SUCKS",
    "NO_ORDERS",
    "HTTPS_GET_FAILED",
    "MISSING_MARKET_PAGE"
};

