/// @file id_vector.cpp
/// @brief Implementation of @ref id_vector_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Saturday October 21 2017
/// * Documentation is generated by doxygen, see html/index.html

#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include "https_get.h"
#include "item_ids.h"
#include "error.h"
#include "json.h"

/// @brief String representations of enumeration symbols.
template <const char* url>
const std::vector<std::string_view> id_vector_t<url>::error_names_ =
{
    "FILE_SIZE_FAILED",
    "FILE_READ_FAILED",
    "FILE_WRITE_FAILED",
    "JSON_SCHEMA_VIOLATION",
    "EVE_SUCKS"
};

/// @brief Default error messages suitable for printing.  Note that
/// some of these are inherently vague without additional information.
template <const char* url>
const std::vector<std::string_view> id_vector_t<url>::default_error_messages_ =
{
    "Error.  Failed to determine size of input file.\n",
    "Error.  Failed to read content from file.\n",
    "Error.  Failed to write content to file.\n",
    "Error.  Json input does not contain the correct fields.\n",
    "Error.  CCP changed something that used to work.\n"
};

