/// @file item_attributes.h
/// @brief Declaration of @ref item_attributes_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Friday October 20 2017
/// * Documentation is generated by doxygen, see documentation/html_out/index.html

#ifndef HEADER_GUARD_ITEM_ATTRIBUTES
#define HEADER_GUARD_ITEM_ATTRIBUTES

#include <fstream>
#include <string_view>
#include <vector>

#include "error.h"
#include "item_attribute.h"
#include "json.h"

class item_ids_t;

/// @brief A group of multiple item attributes.  Useful for bulk fetching,
/// encoding, and decoding possibly using multiple threads.
class item_attributes_t
{
        
    protected:
        
        /// @brief String representations of enumeration symbols.
        static const std::vector<std::string_view> error_names_;
        
        /// @brief Default error messages suitable for printing.  Note that
        /// some of these are inherently vague without additional information.
        static const std::vector<std::string_view> default_error_messages_;
        
        // Try to make all your members protected, even if they don't
        // really need to be.
        
        /// @brief See @ref item_attributes_t
        std::vector<item_attribute_t> data_;
        
    public:
        
        /// @brief Error codes are defined to facilitate programmatic detection and
        /// correction.
        enum class error_code_t
        {
            FILE_SIZE_FAILED,
            FILE_READ_FAILED,
            FILE_WRITE_FAILED,
            JSON_SCHEMA_VIOLATION,
            /// This element must be last
            NUM_ENUMS
        };
        
        typedef error_message_template_t
        <
            error_code_t,
            error_names_,
            default_error_messages_
        > error_message_t;
        
        /// @brief Default constructor
        inline item_attributes_t() = default;
        
        // Add member initialization constructors here
        // Try to use initializer lists when possible.
        
        // Add operators here if desired.
        // inline type operator[](unsigned ix) const;
        // inline type& operator[](unsigned ix);
        
        inline const item_attribute_t& operator[](unsigned ix) const
        {
            return this->data_[ix];
        }
        
        inline item_attribute_t& operator[](unsigned ix)
        {
            return this->data_[ix];
        }
        
        // Add member read and write functions
        // inline type member() const;
        // inline void member(const type& t);
        
        /// @brief Return the number of @ref item_attributes_t stored in this
        /// object.
        inline unsigned size() const
        {
            return this->data_.size();
        }
        
        /// @brief Remove or add new elements starting at the end of storage.
        inline void resize(unsigned new_size)
        {
            this->data_.resize(new_size);
        }
        
        /// @brief Request an increase in storage space.  Does not de-allocate
        /// existing storage.
        inline void reserve(unsigned requested_size)
        {
            this->data_.reserve(requested_size);
        }
        
        /// @brief Extend storage by 1 and insert a new element at the end
        /// of storage.
        inline void emplace_back(const item_attribute_t& new_element)
        {
            this->data_.emplace_back(new_element);
        }
        
        /// @brief Destroy all member elements and set size to zero.
        inline void clear()
        {
            this->data_.clear();
        }
        
        /// @return true if there are no elements in storage.
        inline bool empty() const
        {
            return this->data_.empty();
        }
        
        /// @brief Iterator to the first element in this container.
        inline const item_attribute_t* begin() const
        {
            return &(this->data_[0]);
        }
        
        /// @brief Iterator to the first element in this container.
        inline item_attribute_t* begin()
        {
            return &(this->data_[0]);
        }
        
        /// @brief Iterator one past the end of this container
        inline const item_attribute_t* end() const
        {
            return this->begin() + this->size();
        }
        
        /// @brief Iterator one past the end of this container
        inline item_attribute_t* end()
        {
            return this->begin() + this->size();
        }
        
        /// @brief Fetch the attributes for each item id in the given input
        /// list, replacing previous content.
        ///
        /// @exception item_attribute_t::error_message_t
        /// @exception Json::Exception
        void fetch(const item_ids_t& item_ids);
        
        /// @brief Open a file conforming to schema.json and use it to initialize
        /// this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_file(std::istream& file);
        
        /// @brief Decode serialized content conforming to schema.json and use it
        /// to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_buffer(std::string_view buffer);
        
        /// @brief Extract required data fields from a pre-parsed JSON tree
        /// and use them to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        void read_from_json(const Json::Value& json_root);
        
        /// @brief Serialize the content of this file into a file that
        /// conforms to the schema schema.json.
        void write_to_file
        (
            /// [out] Stream to append serialized object content to.
            std::ostream& file,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Serialize the content of this file into a string that
        /// conforms to the schema schema.json.
        ///
        /// @exception error_message_t
        void write_to_buffer
        (
            /// [out] This string is overwritten with serialzed JSON content.
            std::string& buffer,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Convinence method for pretty initialize-on-construction
        /// syntax.
        inline std::string write_to_buffer
        (
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const {
            std::string buffer;
            this->write_to_buffer(buffer, indent_start, spaces_per_tab);
            return buffer;
        }
        
};

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, item_attributes_t::error_code_t error_code)
{
    stream << item_attributes_t::error_message_t::enum_to_string(error_code);
    return stream;
}

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, const item_attributes_t::error_message_t& error_message)
{
    stream << error_message.message();
    return stream;
}

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, const item_attributes_t& source)
{
    source.write_to_file(stream);
    return stream;
}

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::string& operator<<(std::string& buffer, const item_attributes_t& source)
{
    source.write_to_buffer(buffer);
    return buffer;
}

/// @brief Extraction operator for decoding.
std::istream& operator>>(std::istream& stream, item_attributes_t& destination);

/// @brief Extraction operator for decoding.
inline std::string_view operator>>(std::string_view& buffer, item_attributes_t& destination)
{
    destination.read_from_buffer(buffer);
    return std::string_view();
}

/// @brief Extraction operator for decoding.
inline Json::Value operator>>(const Json::Value& json_root, item_attributes_t& destination)
{
    destination.read_from_json(json_root);
    return Json::Value();
}

#endif // Header Guard

