/// @file item_attribute.h
/// @brief Declaration of @ref item_attribute_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Tuesday October 10 2017
/// * Documentation is generated by doxygen, see documentation/html_out/index.html

#ifndef HEADER_GUARD_ITEM_ATTRIBUTE
#define HEADER_GUARD_ITEM_ATTRIBUTE

#include <fstream>
#include <string_view>
#include <vector>

#include "error.h"
#include "json.h"

/// @brief Contains information about an inventory item that doesn't change
/// often such as its name, integral ID, and possibly other stats like
/// mass and volume in the future.
class item_attribute_t
{
        
    protected:
        
        /// @brief String representations of enumeration symbols.
        static const std::vector<std::string_view> error_names_;
        
        /// @brief Default error messages suitable for printing.  Note that
        /// some of these are inherently vague without additional information.
        static const std::vector<std::string_view> default_error_messages_;
        
        // Try to make all your members protected, even if they don't
        // really need to be.
        
        /// @brief Integral uniqueifier used by the EvE API
        unsigned long id_;
        
        /// @brief The name of this item as it appears in the EvE universe, such
        /// as "Tritanium"
        std::string name_;
        
    public:
        
        /// @brief Error codes are defined to facilitate programmatic detection and
        /// correction.
        enum class error_code_t
        {
            FILE_SIZE_FAILED,
            FILE_READ_FAILED,
            FILE_WRITE_FAILED,
            JSON_SCHEMA_VIOLATION,
            EVE_SUCKS,
            /// This element must be last
            NUM_ENUMS
        };
        
        typedef error_message_template_t
        <
            error_code_t,
            error_names_,
            default_error_messages_
        > error_message_t;
        
        /// @brief Default constructor
        inline item_attribute_t() = default;
        
        // Add member initialization constructors here
        // Try to use initializer lists when possible.
        
        /// @brief Initialization constructor
        inline item_attribute_t(unsigned long id, std::string_view name)
          : id_(id),
            name_(name)
        {
            // All work done in initializer list.
        }
        
        // Add operator[] here if desired.
        // inline type operator[](unsigned ix) const;
        // inline type& operator[](unsigned ix);
        
        /// @brief Return true if two item @ref id_ "IDs" are equal.  Does not
        /// bother checking the other members.
        inline bool operator==(const item_attribute_t& source) const
        {
            return this->id_ == source.id_;
        }
        
        /// @brief Return true if the item ID of this object matches a given ID.
        inline bool operator==(unsigned long id) const
        {
            return this->id_ == id;
        }
        
        /// @brief 1:1 inverse of @ref operator==(const item_attribute_t& source) const "operator==".
        inline bool operator!=(const item_attribute_t& source) const
        {
            return !(*this == source);
        }
        
        inline bool operator!=(unsigned long id) const
        {
            return !(*this == id);
        }
        
        // Add member read and write functions
        // inline type member() const;
        // inline void member(const type& t);
        
        /// @brief Read access to @ref id_.
        inline unsigned long id() const
        {
            return this->id_;
        }
        
        /// @brief Write access to @ref id_.
        inline void id(unsigned long id)
        {
            this->id_ = id;
        }
        
        /// @brief Read access to @ref name_
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        inline const std::string& name() const
        {
            return this->name_;
        }
        
        /// @brief Write access to @ref name_
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        inline void name(std::string_view name)
        {
            this->name_ = name;
        }
        
        /// @brief Connect to the EvE API and pull all of the data associated
        /// with a given item id.
        
        void fetch(unsigned long id);
        
        /// @brief Same as @ref fetch(unsigned long id) but re-uses a reader object
        /// for efficiency.
        void fetch(unsigned long id, Json::CharReader* reader);
        
        /// @brief Open a file conforming to schema.json and use it to initialize
        /// this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_file(std::istream& file);
        
        /// @brief Decode serialized content conforming to schema.json and use it
        /// to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_buffer(std::string_view buffer);
        
        /// @brief Extract required data fields from a pre-parsed JSON tree
        /// and use them to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        void read_from_json(const Json::Value& json_root);
        
        /// @brief Serialize the content of this file into a file that
        /// conforms to the schema schema.json.
        void write_to_file
        (
            /// [out] Stream to append serialized object content to.
            std::ostream& file,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Serialize the content of this file into a string that
        /// conforms to the schema schema.json.
        ///
        /// @exception error_message_t
        void write_to_buffer
        (
            /// [out] This string is overwritten with serialzed JSON content.
            std::string& buffer,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Convinence method for pretty initialize-on-construction
        /// syntax.
        inline std::string write_to_buffer
        (
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const {
            std::string buffer;
            this->write_to_buffer(buffer, indent_start, spaces_per_tab);
            return buffer;
        }
        
};

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, item_attribute_t::error_code_t error_code)
{
    stream << item_attribute_t::error_message_t::enum_to_string(error_code);
    return stream;
}

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, const item_attribute_t::error_message_t& error_message)
{
    stream << error_message.message();
    return stream;
}

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, const item_attribute_t& source)
{
    source.write_to_file(stream);
    return stream;
}

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::string& operator<<(std::string& buffer, const item_attribute_t& source)
{
    source.write_to_buffer(buffer);
    return buffer;
}

/// @brief Extraction operator for decoding.
std::istream& operator>>(std::istream& stream, item_attribute_t& destination);

/// @brief Extraction operator for decoding.
inline std::string_view operator>>(std::string_view& buffer, item_attribute_t& destination)
{
    destination.read_from_buffer(buffer);
    return std::string_view();
}

/// @brief Extraction operator for decoding.
inline Json::Value operator>>(const Json::Value& json_root, item_attribute_t& destination)
{
    destination.read_from_json(json_root);
    return Json::Value();
}

#endif // Header Guard

