/// @file item_ids.cpp
/// @brief Implementation of @ref item_ids_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Sunday October 8 2017
/// * Documentation is generated by doxygen, see html/index.html

#include "item_ids.h"

char item_ids_url[] = "https://esi.tech.ccp.is/latest/universe/types/?datasource=tranquility";
 
std::istream& operator>>(std::istream& stream, item_ids_t& destination)
{
    
    try
    {
        destination.decode(stream);
    } catch (typename item_ids_t::error_message_t error) {
        stream.setstate(std::ios::failbit);
        throw error;
    } catch (Json::Exception error) {
        stream.setstate(std::ios::failbit);
        throw error;
    }
    
    return stream;
    
}
