/// @file station_ids.cpp
/// @brief Implementation of @ref station_ids_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Saturday October 21 2017
/// * Documentation is generated by doxygen, see html/index.html

#include "station_ids.h"

char station_ids_url[] = "https://esi.tech.ccp.is/latest/universe/structures/?datasource=tranquility";

std::istream& operator>>(std::istream& stream, station_ids_t& destination)
{
    
    try
    {
        destination.decode(stream);
    } catch (typename station_ids_t::error_message_t error) {
        stream.setstate(std::ios::failbit);
        throw error;
    } catch (Json::Exception error) {
        stream.setstate(std::ios::failbit);
        throw error;
    }
    
    return stream;
    
}

