/// @file station_market.h
/// @brief Declaration of @ref station_market_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Tuesday November 7 2017
/// * Documentation is generated by doxygen, see html/index.html

#ifndef HEADER_GUARD_STATION_MARKET
#define HEADER_GUARD_STATION_MARKET

#include <fstream>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "error.h"
#include "item_market.h"
#include "json.h"

/// @brief Contains all of the buy and sell orders at a particular station.
class station_market_t
{
        
    public:
        
        /// @brief Default constructor
        inline station_market_t() = default;
        
        // Add member initialization constructors here
        // Try to use initializer lists when possible.
        
        // Add operators here if desired.
        
        /// @brief Iterator to the first element in this container.
        inline std::unordered_map<uint64_t, item_market_t>::const_iterator begin() const
        {
            return this->items_.begin();
        }
        
        /// @brief Iterator to the first element in this container.
        inline std::unordered_map<uint64_t, item_market_t>::iterator begin()
        {
            return this->items_.begin();
        }
        
        /// @brief Iterator one past the end of this container
        inline std::unordered_map<uint64_t, item_market_t>::const_iterator end() const
        {
            return this->items_.end();
        }
        
        /// @brief Iterator one past the end of this container
        inline std::unordered_map<uint64_t, item_market_t>::iterator end()
        {
            return this->items_.end();
        }
        
        // Add member read and write functions
        // inline type member() const;
        // inline void member(const type& t);
        
        inline uint64_t station_id() const
        {
            return this->station_id_;
        }
        
        inline void station_id(uint64_t new_station_id)
        {
            this->station_id_ = new_station_id;
        }
        
        const std::unordered_map<uint64_t, item_market_t>& items() const
        {
            return this->items_;
        }
        
        // Add special-purpose functions here
        
        inline void clear()
        {
            this->items_.clear();
        }
        
        inline void add_new_item_market(const item_market_t& new_item_market)
        {
            this->items_.emplace(new_item_market.item_id(), new_item_market);
        }
        
        /// @brief Open a file conforming to data/json/schema.json and use it to initialize
        /// this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_file(std::istream& file);
        
        /// @brief Decode serialized content conforming to data/json/schema.json and use it
        /// to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_buffer(std::string_view buffer);
        
        /// @brief Extract required data fields from a pre-parsed JSON tree
        /// and use them to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        void read_from_json(const Json::Value& json_root);
        
        /// @brief Serialize the content of this file into a file that
        /// conforms to the schema data/json/schema.json.
        void write_to_file
        (
            /// [out] Stream to append serialized object content to.
            std::ostream& file,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Serialize the content of this file into a string that
        /// conforms to the schema data/json/schema.json.
        ///
        /// @exception error_message_t
        void write_to_buffer
        (
            /// [out] This string is overwritten with serialzed JSON content.
            std::string& buffer,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Convinence method for pretty initialize-on-construction
        /// syntax.
        inline std::string write_to_buffer
        (
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const {
            std::string buffer;
            this->write_to_buffer(buffer, indent_start, spaces_per_tab);
            return buffer;
        }
        
    protected:
        
        // Try to make your members protected, even if they don't have to be.
        
        /// @brief The integral uniquifier for this station, as used by the EvE
        /// Swagger API.
        uint64_t station_id_;
        
        /// @brief All of the items for sale in this station and the bid prices
        /// for these items.
        ///
        /// Each item ID is replicated as a dictionary key for fast lookup.
        std::unordered_map<uint64_t, item_market_t> items_;
        
};

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, const station_market_t& source)
{
    source.write_to_file(stream);
    return stream;
}

/// @brief Extraction operator for decoding.
std::istream& operator>>(std::istream& stream, station_market_t& destination);

#endif // Header Guard

