/// @file util.cpp
/// @brief Implementation of miscelanious general purpose functions
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Thursday November 2 2017
/// * Documentation is generated by doxygen, see documentation/html_out/index.html

#include <string>
#include <string_view>

#include "util.h"

std::string escape_quotes(std::string_view input)
{
    
    std::string ret;
    ret.reserve(input.length());
    
    for (char c : input)
    {
        if (c == '\"')
            ret += '\\';
        ret += c;
    }
    
    return ret;
    
}

