/// @file item_market.h
/// @brief Declaration of @ref item_market_t class
/// 
/// * Contact conor.gardner@arm.com if you have questions about this code.
/// * Date Created = Tuesday November 7 2017
/// * Documentation is generated by doxygen, see html/index.html

#ifndef HEADER_GUARD_ITEM_MARKET
#define HEADER_GUARD_ITEM_MARKET

#include <fstream>
#include <string_view>
#include <vector>

#include "error.h"
#include "json.h"

/// @brief These are all the buy and sell orders at a specific station for one
/// specific item.
class item_market_t
{
        
    public:
        
        /// @brief Default constructor
        inline item_market_t() = default;
        
        // Add member initialization constructors here
        // Try to use initializer lists when possible.
        
        // Add operators here if desired.
        
        // Add member read and write functions
        // inline type member() const;
        // inline void member(const type& t);
        
        uint64_t item_id() const
        {
            return this->item_id_;
        }
        
        void item_id(uint64_t new_item_id)
        {
            this->item_id_ = new_item_id;
        } 
        
        const std::vector<float>& buy_orders() const
        {
            return this->buy_orders_;
        }
        
        const std::vector<float>& sell_orders() const
        {
            return this->sell_orders_;
        }
        
        // Add special-purpose functions here
        
        /// @exception error_message_t
        float min_buy_order() const;
        
        /// @exception error_message_t
        float max_buy_order() const;
        
        /// @exception error_message_t
        float min_sell_order() const;
        
        /// @exception error_message_t
        float max_sell_order() const;
        
        inline void new_buy_order(float buy_price)
        {
            this->buy_orders_.emplace_back(buy_price);
        }
        
        inline void new_sell_order(float sell_price)
        {
            this->sell_orders_.emplace_back(sell_price);
        }
        
        /// @brief Remove all orders that are not the minimum sell order.
        void cull_unavailable_orders();
        
        /// @brief Open a file conforming to data/json/schema.json and use it to initialize
        /// this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_json_file(std::istream& file);
        
        /// @brief Decode serialized content conforming to data/json/schema.json and use it
        /// to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        /// @exception Json::Exception
        void read_from_json_buffer(std::string_view buffer);
        
        /// @brief Extract required data fields from a pre-parsed JSON tree
        /// and use them to initialize this object, clearing previous content.
        ///
        /// @exception error_message_t
        void read_from_json_json(const Json::Value& json_root);
        
        /// @brief Serialize the content of this file into a file that
        /// conforms to the schema data/json/schema.json.
        void write_to_json_file
        (
            /// [out] Stream to append serialized object content to.
            std::ostream& file,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Serialize the content of this file into a string that
        /// conforms to the schema data/json/schema.json.
        ///
        /// @exception error_message_t
        void write_to_json_buffer
        (
            /// [out] This string is overwritten with serialzed JSON content.
            std::string& buffer,
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const;
        
        /// @brief Convinence method for pretty initialize-on-construction
        /// syntax.
        inline std::string write_to_json_buffer
        (
            /// [in] The number of space ' ' characters to prepend to each line
            /// in the serialized output.
            unsigned indent_start = 0,
            /// [in] The number of additional spaces ' ' on top of indent_start
            /// to prepend to each line in the serialized output for each
            /// additional level of nesting.
            ///
            /// Indentation typically increases after each opening bracket '['
            /// or brace '{' and decreases after each closing bracket ']' or
            /// brace '}'.
            unsigned spaces_per_tab = 4
        ) const {
            std::string buffer;
            this->write_to_json_buffer(buffer, indent_start, spaces_per_tab);
            return buffer;
        }
        
    protected:
        
        // Try to make your members protected, even if they don't have to be.
        
        /// @brief The integral uniquifier for this item as used by the Eve
        /// swagger interface.
        uint64_t item_id_;
        
        /// The prices for all active buy bids for this item.
        std::vector<float> buy_orders_;
        
        /// The prices for all active sell bids for this item.
        std::vector<float> sell_orders_;
        
};

/// @brief Convenience alias to allow printing directly via cout or similar.
inline std::ostream& operator<<(std::ostream& stream, const item_market_t& source)
{
    source.write_to_json_file(stream);
    return stream;
}

/// @brief Extraction operator for decoding.
std::istream& operator>>(std::istream& stream, item_market_t& destination);

#endif // Header Guard

